spring:
  application:
    name: MessageAdapter
  ai:
    openai:
      api-key: "placeholder-not-used"
  datasource:
    url: placeholder
    username: placeholder
    password: placeholder
    driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect
          naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      open-in-view: false

    sql:
      init:
        mode: never